spring:
  datasource:
    url: jdbc:mysql://rm-uf6s99wgn42iilrnczo.mysql.rds.aliyuncs.com:3306/tb_order?characterEncoding=utf-8
    username: user_test
    password: abc123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka



